import { Inter } from "next/font/google";
import ParticleProvider from "./components/ParticleProvider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ParticleProvider>
          {children}
        </ParticleProvider>
      </body>
    </html>
  );
}
